---
id: 5755f211-7c96-46fc-aa1f-ece978104aeb
---
classDiagram
    Pessoa <|-- Colaborador
    Colaborador <|-- Administrador
    SubCategoria "1" ..> "*"Item
    SubCategoria "1"<.. "*"Categoria
    Item"*"..>"1"Movimentacao
    Movimentacao"*"..>"1"Estoque
    Doador"1"<.."*"Movimentacao
    Item"*"..>"1"Paciente
    Origem_Destino"2"..>"*"Movimentacao
    Origem_Destino<|..Paciente
    Origem_Destino<|..Doador
    SubCategoria..Unidade
    Estoque"1".."0..*"Lote


    class Pessoa{
        -genericId
        +login(userName, password)
        +recuperarSenha(userName)
    }    

    class Colaborador{
        -userName
        -HashedPassword
        +logOut()
        +gerenciarPerfil()
        +consultarEstoque()
        +gerenciarSubCategorias()
        +genrenciarSolicRetDoacoes()
        +gerenciarMovimentacaoEstoque()       
    }

    class Administrador{
        +gerenciarUsuarios()
        +gerarRelatorios()
        +gerenciarDoadores()
        +dashboardDeIndicadores()
        +gerenciarRemedios()
        +gerenciarAlimentos()
    }

    class Movimentacao{
        -Item item
        -Int quantidade
    }

    class Doador{
        -string nome
        -string telefone
        -string email
        -List~Movimentacao~doacoes
        +fazerMovimentacao(Movimentacao)
    }

    class Item{
        -string nome        
        -tipoItem tipo
        -SubCategoria subcategoria
        
    }

    class Categoria{
        -int id
        -string nome
        -string descricao
        -List ~SubCategoria~ subCategorias
        -string unidade

        +adicionarSubCategoria(SubCategoria)
    }

    class SubCategoria{
        -Categoria categoria
        -int id
        -string nome
        -string descricao
        -Boolean precisaLote
    }

    class Paciente{
        -List~Item~ Emprestimos
        +emprestarItem(Item)
    }

 

    class Lote{
        -Int ID
        -Estoque estoque
        -Date data
    }

    class Estoque{
        -Item item
        -float quantidade
        -List~Lote~ lotes
        +adcicionarItem(item, quantidade)
        +subtrairItem(item, quantidade)
        +alertarValidadeAlimentos(Estoque)
    }

    class Unidade{
        -idUnidade
        -string nome       
    }